apiVersion: apps/v1
kind: Deployment
metadata:
  name: finary-backend-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finary-backend
  template:
    metadata:
      labels:
        app: finary-backend
    spec:
      containers:
      - name: finary-backend
        image: abhishek2803/finary-backend:${{ github.sha }}
        imagePullPolicy: Always
        ports:
          - containerPort: 443
          - containerPort: 80
        volumeMounts:
          - name: ssl-certs-backend
            mountPath: /certs
            readOnly: true
        readinessProbe:
          httpGet:
            path: /
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 15
        livenessProbe:
          httpGet:
            path: /
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 60
        envFrom:
          - secretRef:
              name: finary-secrets
      volumes:
        - name: ssl-certs-backend
          secret:
            secretName: finary-ssl-backend
