apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: finary-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - finary.shop
        - www.finary.shop
        - api.finary.shop
      secretName: finary-tls-secret
  rules:
    - host: finary.shop
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: finary-frontend-service
                port:
                  number: 80
    - host: api.finary.shop
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: finary-backend-service
                port:
                  number: 80
