apiVersion: apps/v1
kind: Deployment
metadata:
  name: finary-frontend-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finary-frontend
  template:
    metadata:
      labels:
        app: finary-frontend
    spec:
      containers:
        - name: finary-frontend
          image: abhishek2803/finary-frontend:${{ github.sha }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
