# === 1. The Frontend Deployment ===
apiVersion: apps/v1
kind: Deployment
metadata:
  name: finary-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finary-frontend
  template:
    metadata:
      labels:
        app: finary-frontend
    spec:
      containers:
      - name: finary-frontend
        # --- YOUR DOCKER HUB IMAGE (the one you just pushed) ---
        image: abhishek2803/finary-frontend:latest
        imagePullPolicy: Always
        ports:
        # Nginx (from your frontend Dockerfile) runs on port 80
        - containerPort: 80

---
# === 2. The Frontend Service ===
apiVersion: v1
kind: Service
metadata:
  name: finary-frontend-service
spec:
  # This creates a new, separate Azure Load Balancer
  type: LoadBalancer
  selector:
    app: finary-frontend
  ports:
  - protocol: TCP
    # The world connects to port 80 (standard http)
    port: 80
    # It sends traffic to your container's port 80
    targetPort: 80